"""Captions + location for brand gallery media, keyed by filename stem (g00..g26, film)."""

CAPTIONS = {
    "film": {"caption": "A day at the source", "location": "Keneth Global"},
    "g00": {"caption": "Freshly milled cumin seeds", "location": "Spice market, India"},
    "g01": {"caption": "Green cardamom, sun-drying", "location": "Spice estate, India"},
    "g02": {"caption": "Whole cashews, hand-picked", "location": "Dry-fruit market, India"},
    "g03": {"caption": "Morning at the fishing harbour", "location": "Kochi, India"},
    "g04": {"caption": "Cinnamon bark & pepper, curing", "location": "Spice warehouse, India"},
    "g05": {"caption": "Star anise, whole", "location": "Spice market, India"},
    "g06": {"caption": "Hand-sorted cloves", "location": "Spice market, India"},
    "g07": {"caption": "Roasted pistachios", "location": "Dry-fruit market, India"},
    "g08": {"caption": "Grade-AAA green cardamom", "location": "Spice estate, India"},
    "g09": {"caption": "Cloves drying in the sun", "location": "Spice warehouse, India"},
    "g10": {"caption": "Black cardamom, freshly dried", "location": "Spice warehouse, India"},
    "g11": {"caption": "Rows of sun-dried spice", "location": "Spice warehouse, India"},
    "g12": {"caption": "Medjool dates, by the kilo", "location": "Dry-fruit souk"},
    "g13": {"caption": "Star anise, laid out to dry", "location": "Spice market, India"},
    "g14": {"caption": "Golden dates, ready to pack", "location": "Dry-fruit market"},
    "g15": {"caption": "A table of whole spices", "location": "Spice market, India"},
    "g16": {"caption": "Soft black dates", "location": "Dry-fruit souk"},
    "g17": {"caption": "Amber dates, hand-selected", "location": "Dry-fruit market"},
    "g18": {"caption": "Cinnamon quills & white pepper", "location": "Spice warehouse, India"},
    "g19": {"caption": "Dried fruit, freshly cured", "location": "Dry-fruit market"},
    "g20": {"caption": "The people behind Keneth", "location": "On the road, India"},
    "g21": {"caption": "Boats at the jetty", "location": "Kochi, India"},
    "g22": {"caption": "Dubai dates, counter-fresh", "location": "Dry-fruit market"},
    "g23": {"caption": "Sundown over the harbour", "location": "Kochi, India"},
    "g24": {"caption": "A bowl of ripe dates", "location": "Dry-fruit souk"},
    "g25": {"caption": "Dusk on the backwaters", "location": "Kerala, India"},
    "g26": {"caption": "Spice trays at the market", "location": "Spice market, India"},
}
