"""Individual products imported from owner-uploaded photographs (Oct 2026).

Each distinct design in the uploaded photo folders becomes its own product.
`_sources` references (folder_key, index) into /app/backend/uploaded_src/<folder>,
resolved against the sorted file list — the image pipeline converts them to the
slug-named PNGs that reconcile_static_images attaches on startup.

REMOVED_SLUGS are the old grouped listings these individuals replace; the server
deletes them on startup so nothing duplicates.
"""

REMOVED_SLUGS = [
    "oxidised-silver-jhumka",
    "beaded-choker-set",
    "felt-christmas-ornament-set",
    "figurine-napkin-rings",
    "carved-brass-napkin-rings",
    "wire-mesh-napkin-rings",
    "velvet-embroidered-stocking",
    "beaded-christmas-placemats",
    "embroidered-velvet-tree-skirt",
    "pure-leather-wallet",
]


def _p(slug, name, vertical, category, price, unit, short, long, badge, sources):
    return {
        "slug": slug,
        "name": {"en": name},
        "vertical": vertical,
        "category": category,
        "price_eur": float(price),
        "unit": unit,
        "short_description": {"en": short},
        "long_description": {"en": long},
        "image_prompt": "",
        "image_hint": "",
        "badge": {"en": badge} if badge else None,
        "_sources": sources,
    }


UPLOADED = [
    # ==================== ARTIFICIAL JEWELRY ====================
    _p("silver-jhumka-earrings", "Oxidised Silver Jhumka Earrings", "artificial-jewelry", "earrings",
       28, "pair", "Classic oxidised-silver dome jhumkas with rose studs.",
       "Hand-finished oxidised silver jhumka earrings with carved rose studs and a bell-shaped dome drop. Light enough for all-day wear and a timeless match for both ethnic and modern outfits.",
       "Handcrafted", [("jewellery", 2)]),
    _p("grand-silver-jhumka-earrings", "Grand Silver Temple Jhumka Earrings", "artificial-jewelry", "earrings",
       34, "pair", "Oversized statement jhumkas in antique silver.",
       "An oversized pair of temple-style jhumka earrings in antique oxidised silver, layered with intricate filigree and a full ring of bell drops. A true statement piece for festive and bridal looks.",
       "Statement", [("jewellery", 10), ("ornaments", 25)]),
    _p("ruby-emerald-drop-earrings", "Ruby & Emerald Pearl-Drop Earrings", "artificial-jewelry", "earrings",
       26, "pair", "Kundan-set drops with ruby, emerald and pearl beads.",
       "Delicate kundan-set earrings dripping with ruby-red and emerald-green glass beads and seed pearls. Hand-assembled on silver-tone wire for a rich, regal finish.",
       "Festive", [("jewellery", 4)]),
    _p("kundan-pendant-necklace", "Gold Kundan Pendant Necklace", "artificial-jewelry", "necklaces",
       39, "piece", "Uncut-glass kundan pendant on a beaded strand.",
       "A square kundan pendant pave-set with pearls and coloured stones, suspended on a hand-strung bead strand. Vintage temple-jewelry character in a lightweight everyday piece.",
       "Kundan", [("jewellery", 5)]),
    _p("pearl-ruby-emerald-necklace-set", "Pearl, Ruby & Emerald Necklace Set", "artificial-jewelry", "necklaces",
       72, "set", "Choker with matching earrings in pearl, ruby and emerald.",
       "A regal necklace-and-earring set strung with freshwater-style pearls and ruby-and-emerald beads around an ornate gold-tone pendant. A complete bridal-feel set for weddings and celebrations.",
       "Bridal Set", [("jewellery", 6)]),
    _p("gold-pearl-drop-pendant", "Gold Pearl-Drop Temple Pendant", "artificial-jewelry", "necklaces",
       42, "piece", "Temple pendant with pearl and ruby drops.",
       "A gold-tone temple pendant studded with pearls and a single ruby drop, finished with a fringe of seed-pearl dangles. Pairs effortlessly with silk and handloom.",
       "Temple", [("jewellery", 7)]),
    _p("ruby-emerald-gold-choker", "Ruby-Emerald Gold Beaded Choker", "artificial-jewelry", "necklaces",
       58, "set", "Multi-strand bead choker with matching studs.",
       "A multi-strand choker of ruby-red and emerald-green beads with pearl accents and a carved gold-tone centrepiece, complete with matching studs. Rich festive colour that sits close to the neck.",
       "Choker", [("jewellery", 9), ("ornaments", 24)]),
    _p("pearl-silver-pendant-choker", "Pearl & Silver-Pendant Bead Choker", "artificial-jewelry", "necklaces",
       54, "set", "Ruby-emerald bead choker with a silver pendant.",
       "A four-strand ruby-and-emerald bead choker centred on an openwork silver-tone pendant with carved drops, finished with matching earrings. A regal heirloom-feel set for special occasions.",
       "Heirloom", [("jewellery", 11)]),
    _p("multicolour-glass-bead-strands", "Multicolour Glass Bead Strands", "artificial-jewelry", "necklaces",
       22, "set", "Loose polished glass bead ovals in jewel tones.",
       "A selection of polished oval glass beads in emerald, amethyst and smoky jewel tones — ready to layer or restring. A versatile accent for the jewellery lover.",
       None, [("ornaments", 26)]),
    _p("antique-brass-bangles", "Antique Brass Bangle Pair", "artificial-jewelry", "bangles",
       29, "pair", "Smooth antique-finish brass bangles.",
       "A pair of smooth, substantial brass bangles in a warm antique finish. Minimal and sculptural, they stack beautifully with ethnic and everyday wrists alike.",
       None, [("ornaments", 6)]),

    # ==================== LEATHER WALLETS ====================
    _p("brown-leather-bifold-wallet", "Brown Pure-Leather Bi-Fold Wallet", "artificial-jewelry", "leather-accessories",
       36, "piece", "Full-grain brown leather wallet with card slots.",
       "A slim bi-fold wallet in rich brown full-grain leather, with multiple card slots and a note compartment. Hand-stitched and built to age beautifully with daily use.",
       "Pure Leather", [("wallets", 2), ("wallets", 0), ("wallets", 1), ("wallets", 5)]),
    _p("navy-leather-bifold-wallet", "Navy Pure-Leather Bi-Fold Wallet", "artificial-jewelry", "leather-accessories",
       38, "piece", "Classic navy full-grain leather bi-fold.",
       "A clean navy bi-fold crafted from full-grain pure leather, with neat card slots and a full-length note pocket. A smart, understated everyday essential.",
       "Pure Leather", [("wallets", 3)]),
    _p("black-leather-bifold-wallet", "Black Pure-Leather Bi-Fold Wallet", "artificial-jewelry", "leather-accessories",
       36, "piece", "Minimal black full-grain leather bi-fold.",
       "A minimal black bi-fold wallet in full-grain pure leather, slim enough for a pocket yet roomy for cards and notes. Hand-stitched edges for lasting durability.",
       "Pure Leather", [("wallets", 4)]),

    # ==================== CHRISTMAS ORNAMENTS ====================
    _p("red-felt-tree-ornament", "Beaded Felt Christmas Tree Ornament", "christmas-decor", "ornaments",
       14, "piece", "Hand-beaded red felt tree ornament.",
       "A plush red felt Christmas-tree ornament hand-embroidered with zari and sequins and outlined in beadwork. A charming artisan-made bauble to hang on the tree or dress a gift.",
       "Artisan Made", [("ornaments", 0)]),
    _p("felt-figure-ornament", "Embroidered Felt Figure Ornament", "christmas-decor", "ornaments",
       14, "piece", "Hand-stitched felt character ornament.",
       "A whimsical hand-stitched felt figure ornament finished with fine embroidery and bead detail. Soft, light and full of folk-art character.",
       "Artisan Made", [("ornaments", 1)]),
    _p("jute-ball-ornaments", "Jute Woven Ball Ornaments", "christmas-decor", "ornaments",
       24, "set of 6", "Colourful hand-wound jute baubles.",
       "A cluster of hand-wound jute ball ornaments in festive pink, teal and red with a gilded centre bauble. Natural, textural and eco-friendly decorations that add warmth to any tree.",
       "Eco Friendly", [("ornaments", 15), ("ornaments", 2), ("ornaments", 16), ("ornaments", 17)]),
    _p("gold-zardozi-leaf-ornament", "Gold Zardozi Leaf Ornament", "christmas-decor", "ornaments",
       16, "piece", "Raised gold zardozi leaf ornament.",
       "A sculptural leaf ornament worked in raised gold zardozi embroidery over a padded base. A luxe metallic accent for the tree, wreath or gift wrap.",
       None, [("ornaments", 3)]),
    _p("peacock-felt-ornament", "Peacock Bird Felt Ornament", "christmas-decor", "ornaments",
       15, "piece", "Hand-embroidered peacock bird ornament.",
       "A blue peacock-bird ornament hand-embroidered on felt with beadwork and zari outlining. A colourful folk-art hanging that stands out on any tree.",
       "Artisan Made", [("ornaments", 7)]),
    _p("bee-felt-ornament", "Golden Bee Felt Ornament", "christmas-decor", "ornaments",
       15, "piece", "Beaded bee ornament in gold and black.",
       "A charming honey-bee ornament hand-embroidered in gold and black zari with sheer organza wings. A delicate artisan-made accent for tree or gift.",
       "Artisan Made", [("ornaments", 8)]),
    _p("gold-glass-ball-ornament", "Gilded Glass Ball Ornament", "christmas-decor", "ornaments",
       18, "piece", "Mirror-gold glass ball in a painted dish.",
       "A lustrous mirror-gold glass ball ornament resting in a hand-painted enamel dish. Reflects candlelight beautifully as a centrepiece or tree ornament.",
       None, [("ornaments", 9)]),
    _p("gold-felt-star-ornament", "Embroidered Gold Star Ornament", "christmas-decor", "ornaments",
       13, "piece", "Padded gold felt star with bead edging.",
       "A padded gold felt star ornament hand-finished with sequins and a beaded edge. A classic topper-style hanging that catches the light on the tree.",
       "Artisan Made", [("ornaments", 10)]),
    _p("purple-felt-star-ornament", "Beaded Purple Star Ornament", "christmas-decor", "ornaments",
       13, "piece", "Jewel-purple felt star with beadwork.",
       "A jewel-toned purple felt star ornament scattered with sequins and bead detailing. A rich, unexpected colour for a festive tree.",
       "Artisan Made", [("ornaments", 11)]),
    _p("beaded-flower-ornament", "Beaded Flower Ornament", "christmas-decor", "ornaments",
       14, "piece", "Hand-beaded floral medallion ornament.",
       "A hand-beaded flower medallion ornament worked in soft metallic threads and seed beads. A delicate, intricate hanging for tree or garland.",
       "Artisan Made", [("ornaments", 12)]),
    _p("black-beaded-heart-ornament", "Beaded Heart Ornament", "christmas-decor", "ornaments",
       14, "piece", "Padded heart ornament in black and silver beadwork.",
       "A padded heart ornament densely hand-beaded in black and silver with a looped hanger. A romantic, tactile accent for the festive tree.",
       "Artisan Made", [("ornaments", 13)]),
    _p("teacup-ornament", "Royal Teacup Ornament", "christmas-decor", "ornaments",
       16, "piece", "Gilded red-and-gold teacup ornament.",
       "A whimsical teacup ornament painted in regal red and gold with a crown motif. A playful heirloom-style hanging for tea lovers and collectors.",
       None, [("ornaments", 14)]),
    _p("red-felt-star-ornament", "Embroidered Red Star Ornament", "christmas-decor", "ornaments",
       13, "piece", "Red felt star ornament with 'Joy' detail.",
       "A cheerful red felt star ornament hand-embroidered with a festive 'Joy' motif and beaded edge. A warm, classic hanging for the holiday tree.",
       "Artisan Made", [("ornaments", 19)]),
    _p("gold-chandelier-ornament", "Zardozi Chandelier Ornament", "christmas-decor", "ornaments",
       22, "piece", "Raised gold zardozi chandelier ornament.",
       "An ornate chandelier-shaped ornament worked in raised gold zardozi with pearl drops. A show-stopping metallic hanging for a statement tree.",
       "Limited", [("ornaments", 20)]),
    _p("gold-reindeer-ornament", "Gold Reindeer Ornament", "christmas-decor", "ornaments",
       16, "piece", "Embroidered gold reindeer ornament.",
       "A leaping reindeer ornament worked in gold zardozi and sequins on a padded base. A festive classic for tree, wreath or gift topper.",
       None, [("ornaments", 21)]),
    _p("green-beaded-heart-ornament", "Green Beaded Heart Ornament", "christmas-decor", "ornaments",
       14, "piece", "Teal-and-gold beaded heart ornament.",
       "A padded heart ornament hand-beaded in teal and gold with a decorative border. A rich, tactile accent that pairs with the black beaded heart for a set.",
       "Artisan Made", [("ornaments", 22)]),
    _p("mini-bauble-ornament-set", "Mini Wound-Bauble Ornament Set", "christmas-decor", "ornaments",
       20, "set", "Cluster of small thread-wound baubles.",
       "A cheerful cluster of small hand-wound baubles in candy brights and gold. Scatter them across the tree or bundle into a gift bow.",
       "Set", [("ornaments", 27)]),

    # ==================== CHRISTMAS STOCKINGS ====================
    _p("holly-tree-velvet-stocking", "Holly Tree Velvet Stocking", "christmas-decor", "stockings",
       34, "piece", "Red velvet stocking with embroidered tree.",
       "A plush red velvet Christmas stocking embroidered with a golden Christmas tree and scrollwork, finished with a soft cuff. Heirloom quality — personalisation available on request.",
       "Velvet", [("stockings", 0)]),
    _p("maroon-gold-tassel-stocking", "Maroon Gold-Tassel Stocking", "christmas-decor", "stockings",
       38, "piece", "Maroon stocking with brocade cuff and tassel.",
       "A richly embroidered maroon velvet stocking with a gold brocade cuff and a hanging silk tassel. A luxurious mantel piece with real artisan detail.",
       "Velvet", [("stockings", 1)]),
    _p("red-scroll-velvet-stocking", "Red Scroll Velvet Stocking", "christmas-decor", "stockings",
       34, "piece", "Red velvet stocking with white scrollwork.",
       "A deep red velvet stocking embroidered with flowing white scroll and snowflake motifs. Classic Christmas character for the fireplace.",
       "Velvet", [("stockings", 2)]),
    _p("burgundy-floral-stocking", "Burgundy Floral Brocade Stocking", "christmas-decor", "stockings",
       36, "piece", "Burgundy brocade stocking with gold florals.",
       "A burgundy stocking worked in gold floral brocade and embroidery with a plush cuff. An opulent, old-world piece to hang on the mantel.",
       "Velvet", [("stockings", 3)]),
    _p("snowflake-velvet-stocking", "Snowflake Velvet Stocking", "christmas-decor", "stockings",
       34, "piece", "Red velvet stocking with beaded snowflakes.",
       "A red velvet stocking scattered with silver beaded snowflakes and finished with a soft grey cuff and tassel. Sparkling seasonal detail for the tree or fireplace.",
       "Velvet", [("stockings", 4)]),
    _p("red-holly-ribbon-stocking", "Red Holly & Ribbon Stocking", "christmas-decor", "stockings",
       34, "piece", "Red velvet stocking with holly and ribbon.",
       "A red velvet stocking embroidered with holly leaves, berries and a flowing ribbon in gold and green. A warm, traditional design for the holiday mantel.",
       "Velvet", [("stockings", 5)]),
    _p("burgundy-fan-stocking", "Burgundy Fan-Pattern Stocking", "christmas-decor", "stockings",
       38, "piece", "Burgundy stocking with gold fan embroidery.",
       "A striking burgundy velvet stocking embroidered with a gold scalloped fan pattern and beadwork. A bold, geometric take on the classic Christmas stocking.",
       "Velvet", [("stockings", 6)]),

    # ==================== CHRISTMAS COASTERS / TABLE MATS ====================
    _p("poinsettia-beaded-coaster", "Poinsettia Beaded Table Mat", "christmas-decor", "coasters",
       18, "piece", "Round beaded poinsettia table mat.",
       "A round hand-beaded festive table mat centred on a poinsettia bloom in red and gold. Individually crafted to add a rich, tactile centrepiece to the holiday table.",
       "Hand Beaded", [("coasters", 0), ("coasters", 2)]),
    _p("santa-face-coaster", "Santa Face Table Mat", "christmas-decor", "coasters",
       18, "piece", "Round embroidered Santa-face table mat.",
       "A cheerful round table mat appliqued and embroidered with a jolly Santa face in red, white and green. A playful festive accent for place settings or side tables.",
       "Hand Beaded", [("coasters", 1)]),
    _p("reindeer-coaster", "Reindeer Table Mat", "christmas-decor", "coasters",
       18, "piece", "Round red mat with golden reindeer.",
       "A round red table mat embroidered with a leaping golden reindeer. A clean, graphic festive motif that dresses the table beautifully.",
       "Hand Beaded", [("coasters", 3)]),
    _p("snowman-coaster", "Snowman Table Mat", "christmas-decor", "coasters",
       18, "piece", "Round red mat with embroidered snowman.",
       "A round red table mat appliqued with a smiling snowman in hat and scarf. A friendly, family-favourite design for the holiday table.",
       "Hand Beaded", [("coasters", 4)]),
    _p("santa-coaster", "Santa Figure Table Mat", "christmas-decor", "coasters",
       18, "piece", "Round mat with full-figure Santa.",
       "A round table mat embroidered with a full-figure Santa carrying his candy cane. A warm, traditional accent for festive place settings.",
       "Hand Beaded", [("coasters", 5)]),
    _p("framed-snowman-coaster", "Framed Snowman Table Mat", "christmas-decor", "coasters",
       18, "piece", "Grey mat with framed snowman motif.",
       "A round grey table mat with a framed snowman medallion and scalloped red edge. A softer, contemporary palette for the modern holiday table.",
       "Hand Beaded", [("coasters", 6)]),
    _p("snowflake-coaster", "Snowflake Table Mat", "christmas-decor", "coasters",
       18, "piece", "Round red mat with silver snowflake.",
       "A round red table mat centred on a sparkling silver beaded snowflake. A crisp, wintry motif that works through the whole season.",
       "Hand Beaded", [("coasters", 7)]),

    # ==================== CHRISTMAS TREE SKIRTS ====================
    _p("red-velvet-floral-tree-skirt", "Red Velvet Floral Tree Skirt", "christmas-decor", "tree-skirts",
       72, "piece", "Red velvet tree skirt with gold floral zari.",
       "A sumptuous red velvet Christmas tree skirt hand-embroidered with gold zari florals and beaded snowflakes. A rich, heirloom-quality base to crown your tree.",
       "Velvet", [("tree_skirts", 0)]),
    _p("gold-embroidered-tree-skirt", "Gold Embroidered Tree Skirt", "christmas-decor", "tree-skirts",
       78, "piece", "Antique-gold tree skirt with tassel ties.",
       "An antique-gold velvet tree skirt worked in dense zari scrollwork and finished with silk tassel ties. A luxe, warm-metallic alternative to classic red.",
       "Gold", [("tree_skirts", 1)]),
    _p("green-velvet-tree-skirt", "Forest Green Velvet Tree Skirt", "christmas-decor", "tree-skirts",
       72, "piece", "Green velvet tree skirt with gold embroidery.",
       "A forest-green velvet tree skirt embroidered with gold foliage and finished with tassel ties. A deep, natural tone that complements green and frosted trees.",
       "Velvet", [("tree_skirts", 2)]),
    _p("red-bordered-velvet-tree-skirt", "Red Bordered Velvet Tree Skirt", "christmas-decor", "tree-skirts",
       68, "piece", "Red velvet skirt with embroidered border band.",
       "A deep red velvet tree skirt with a broad hand-embroidered border band in gold and pearl, finished with tassel ties. A bold, graphic crown for the base of your tree.",
       "Velvet", [("tree_skirts", 3)]),

    # ==================== HOME FURNISHING — NAPKIN RINGS ====================
    _p("brass-lattice-napkin-ring", "Brass Lattice Napkin Ring", "home-furnishing", "napkin-rings",
       16, "piece", "Wide diamond-cut brass napkin ring.",
       "A wide-band napkin ring in warm brass with an all-over diamond lattice cut. A substantial, timeless table accent that dresses up linen napkins instantly.",
       None, [("napkin_rings", 0)]),
    _p("gold-engraved-napkin-ring", "Gold Engraved Band Napkin Ring", "home-furnishing", "napkin-rings",
       16, "piece", "Etched gold-tone band napkin ring.",
       "A classic wide-band napkin ring in gold-tone metal with delicate floral engraving. A warm, traditional finishing touch for everyday and festive tables.",
       None, [("napkin_rings", 1), ("napkin_rings", 32)]),
    _p("silver-embossed-napkin-ring", "Silver Embossed Napkin Ring", "home-furnishing", "napkin-rings",
       16, "piece", "Silver-tone band with embossed pattern.",
       "A silver-tone napkin ring with a softly embossed scroll pattern around a wide band. Understated shimmer for contemporary tablescapes.",
       None, [("napkin_rings", 2)]),
    _p("palm-tree-curtain-holdback", "Palm Tree Brass Curtain Holdback", "home-furnishing", "curtain-holdbacks",
       28, "piece", "Cast-brass palm-tree curtain tie-back.",
       "A sculptural cast-brass curtain holdback shaped as a palm tree, mounted on a sturdy arm. A decorative way to gather drapes in style.",
       None, [("napkin_rings", 3)]),
    _p("hammered-silver-napkin-ring", "Hammered Silver Napkin Ring", "home-furnishing", "napkin-rings",
       16, "piece", "Tapered silver ring with hammered texture.",
       "A gently tapered napkin ring in silver-tone metal with an all-over hammered texture (style NR-5025). Catches the light beautifully across the table.",
       None, [("napkin_rings", 4), ("napkin_rings", 33)]),
    _p("engraved-silver-napkin-ring", "Engraved Silver Napkin Ring", "home-furnishing", "napkin-rings",
       16, "piece", "Silver band with floral engraving.",
       "A wide silver-tone napkin ring finished with fine floral engraving (style NR-5468). A refined, classic accent for linen napkins.",
       None, [("napkin_rings", 5)]),
    _p("angel-brass-napkin-ring", "Angel Figurine Brass Napkin Ring", "home-furnishing", "napkin-rings",
       18, "piece", "Antique-brass napkin ring with angel figure.",
       "A charming napkin ring topped with a cast angel figurine in antique brass. A festive, sculptural finishing touch for the holiday table.",
       None, [("napkin_rings", 6)]),
    _p("butterfly-brass-napkin-ring", "Butterfly Brass Napkin Ring", "home-furnishing", "napkin-rings",
       18, "piece", "Gold-tone napkin ring with butterfly.",
       "A delicate napkin ring crowned with a filigree butterfly in gold-tone brass. A light, pretty accent for spring and celebration tables.",
       None, [("napkin_rings", 7), ("napkin_rings", 34)]),
    _p("rose-leaf-napkin-ring", "Rose & Leaf Brass Napkin Ring", "home-furnishing", "napkin-rings",
       18, "piece", "Gold napkin ring with rose and leaf motif.",
       "A cast-brass napkin ring finished with a rose-and-leaf motif in antique gold. A romantic, botanical touch for dressed tables.",
       None, [("napkin_rings", 8)]),
    _p("woven-cane-napkin-ring", "Woven Cane Napkin Ring", "home-furnishing", "napkin-rings",
       14, "piece", "Natural hand-woven cane napkin ring.",
       "A napkin ring hand-woven from natural cane for an organic, rustic feel. Pairs beautifully with linen and earthenware for relaxed tablescapes.",
       None, [("napkin_rings", 9)]),
    _p("gold-wire-ball-napkin-ring", "Gold Wire-Ball Napkin Ring", "home-furnishing", "napkin-rings",
       18, "piece", "Airy hand-coiled gold wire napkin ring.",
       "A light, airy napkin ring hand-coiled from gold-tone wire into a nest-like ball. Modern and textural, it brings a soft shimmer to the table.",
       None, [("napkin_rings", 10)]),
    _p("gold-band-napkin-ring", "Plain Gold Band Napkin Ring", "home-furnishing", "napkin-rings",
       14, "piece", "Simple polished gold-tone band.",
       "A clean, polished gold-tone band napkin ring with no ornament — the quiet, versatile choice that suits any napkin and setting.",
       None, [("napkin_rings", 11), ("napkin_rings", 17)]),
    _p("black-braided-napkin-ring", "Black Braided Napkin Ring", "home-furnishing", "napkin-rings",
       14, "piece", "Dark braided-texture napkin ring.",
       "A napkin ring with a dark, braided rope texture for a moody, tactile table accent. Pairs well with deep linens and matte stoneware.",
       None, [("napkin_rings", 12)]),
    _p("wooden-napkin-rings", "Natural Wooden Napkin Rings", "home-furnishing", "napkin-rings",
       16, "set of 2", "Smooth turned-wood napkin rings.",
       "Smooth turned-wood napkin rings with a natural grain finish. Warm, simple and sustainable for everyday and rustic tables.",
       "Set of 2", [("napkin_rings", 13), ("napkin_rings", 14)]),
    _p("painted-lacquer-napkin-rings", "Painted Lacquer Napkin Rings", "home-furnishing", "napkin-rings",
       22, "set of 4", "Hand-painted lacquered wooden rings.",
       "A colourful stack of hand-painted, lacquered wooden napkin rings in festive folk patterns. A joyful pop of colour for the table.",
       "Set of 4", [("napkin_rings", 15)]),
    _p("brass-plain-napkin-rings", "Plain Brass Napkin Rings", "home-furnishing", "napkin-rings",
       20, "set of 4", "Simple polished brass napkin rings.",
       "A set of simple, polished brass napkin rings with a soft rounded profile. Warm, classic and endlessly versatile.",
       "Set of 4", [("napkin_rings", 16), ("napkin_rings", 29)]),
    _p("two-tone-metal-napkin-rings", "Two-Tone Metal Napkin Rings", "home-furnishing", "napkin-rings",
       20, "set of 2", "Silver and gold-tone band pair.",
       "A pair of wide band napkin rings in complementary silver and gold tones. Mix and match for an easy, elevated table.",
       "Set of 2", [("napkin_rings", 18)]),
    _p("matte-gold-cuff-napkin-ring", "Matte Gold Cuff Napkin Ring", "home-furnishing", "napkin-rings",
       18, "piece", "Wide matte gold cuff with cross-hatch.",
       "A wide, substantial napkin ring in matte gold with a subtle cross-hatch texture. Bold and contemporary for a statement table.",
       None, [("napkin_rings", 19)]),
    _p("silver-beaded-band-napkin-ring", "Silver Beaded-Band Napkin Ring", "home-furnishing", "napkin-rings",
       16, "piece", "Silver band with beaded edging.",
       "A silver-tone napkin ring finished with a fine beaded edge for a touch of detail. A refined, light accent for linen napkins.",
       None, [("napkin_rings", 20), ("napkin_rings", 35)]),
    _p("reindeer-brass-napkin-rings", "Reindeer Brass Napkin Rings", "home-furnishing", "napkin-rings",
       22, "set of 2", "Silver and gold reindeer napkin rings.",
       "A festive pair of napkin rings topped with cast reindeer figures in silver and gold tones. A playful, sculptural finish for the holiday table.",
       "Set of 2", [("napkin_rings", 21)]),
    _p("rope-edge-silver-napkin-ring", "Rope-Edge Silver Napkin Ring", "home-furnishing", "napkin-rings",
       16, "piece", "Silver ring with rope-twist borders.",
       "A silver-tone napkin ring framed by twin rope-twist borders. A classic nautical-meets-formal detail for dressed tables.",
       None, [("napkin_rings", 23)]),
    _p("antique-leaf-cuff-napkin-ring", "Antique Leaf Cuff Napkin Ring", "home-furnishing", "napkin-rings",
       18, "piece", "Blackened-gold cuff with leaf relief.",
       "A wide cuff-style napkin ring in blackened gold with a raised leaf relief. Rich, antique character for an opulent table.",
       None, [("napkin_rings", 24)]),
    _p("antique-lattice-cuff-napkin-ring", "Antique Lattice Cuff Napkin Ring", "home-furnishing", "napkin-rings",
       18, "piece", "Blackened-gold open lattice cuff.",
       "A wide cuff napkin ring with an open lattice weave in antique blackened gold. Dramatic and architectural for statement settings.",
       None, [("napkin_rings", 25)]),
    _p("brass-twist-napkin-rings", "Brass Twist Napkin Rings", "home-furnishing", "napkin-rings",
       18, "set of 2", "Coiled brass-wire twist rings.",
       "A pair of napkin rings coiled from brass-tone wire into an open twist. Light, modern and textural for contemporary tables.",
       "Set of 2", [("napkin_rings", 26)]),
    _p("turtle-curtain-holdback", "Turtle Brass Curtain Holdback", "home-furnishing", "curtain-holdbacks",
       28, "piece", "Cast-metal turtle curtain tie-back.",
       "A characterful curtain holdback featuring a cast turtle on a mounting arm. A decorative, conversation-starting way to gather drapes.",
       None, [("napkin_rings", 27)]),
    _p("gold-spiral-napkin-rings", "Gold Spiral Napkin Rings", "home-furnishing", "napkin-rings",
       18, "set of 2", "Open gold-tone spiral napkin rings.",
       "A pair of napkin rings formed from a continuous gold-tone spiral. Sculptural and airy, they add quiet movement to the table.",
       "Set of 2", [("napkin_rings", 28)]),
    _p("gold-star-napkin-ring", "Gold Star Napkin Ring", "home-furnishing", "napkin-rings",
       18, "piece", "Napkin ring topped with a gold star.",
       "A napkin ring crowned with a dimensional gold star — a festive, cheerful finish for holiday and celebration tables.",
       None, [("napkin_rings", 30)]),
    _p("bronze-leaf-napkin-ring", "Bronze Leaf Napkin Ring", "home-furnishing", "napkin-rings",
       18, "piece", "Bronze napkin ring with leaf spray.",
       "A napkin ring finished with a sculpted leaf spray in warm bronze. A natural, botanical accent that suits autumn and festive tables alike.",
       None, [("napkin_rings", 31)]),
    _p("hammered-brass-napkin-ring", "Hammered Brass Napkin Ring", "home-furnishing", "napkin-rings",
       16, "piece", "Polished brass ring with hammered finish.",
       "A classic napkin ring in polished brass with a lightly hammered finish. Warm, timeless and perfect for everyday and festive linens.",
       None, [("napkin_rings", 36)]),
    _p("angel-wings-napkin-ring", "Angel Wings Brass Napkin Ring", "home-furnishing", "napkin-rings",
       18, "piece", "Gold napkin ring with angel-wing motif.",
       "A napkin ring finished with a pair of outstretched angel wings in gold-tone brass. A graceful, festive detail for the holiday table.",
       None, [("napkin_rings", 37)]),

    # ==================== HOME FURNISHING — VOTIVE / CANDLE ====================
    _p("blackened-gold-leaf-votive", "Blackened-Gold Leaf Votive Holder", "home-furnishing", "candle-holders",
       30, "piece", "Antique-gold votive with leaf relief.",
       "A cast votive candle holder in blackened antique gold with a raised leaf relief, throwing a warm patterned glow when lit. Fits a standard tea-light or small pillar.",
       "Hand Cast", [("ornaments", 4), ("ornaments", 5)]),
    _p("engraved-brass-votive", "Engraved Brass Votive Holder", "home-furnishing", "candle-holders",
       28, "piece", "Gold engraved-band votive holder.",
       "A wide-band votive candle holder in engraved gold-tone brass. A compact, glowing accent for mantels, tables and windowsills.",
       "Hand Cast", [("ornaments", 18)]),

    # ==================== HOME FURNISHING — WALL HANGING ====================
    _p("royal-zari-arch-wall-hanging", "Royal Zari Arch Wall Hanging", "home-furnishing", "wall-hangings",
       175, "piece", "Gold zari arch-and-blossom velvet tapestry.",
       "A grand wall hanging hand-embroidered in raised gold zari on deep blue velvet, depicting a blossoming arch motif within a decorative border. A statement heirloom tapestry for feature walls and entryways.",
       "Heirloom", [("wall_hangings", 1)]),

    # ==================== SCREENSHOT / ADDITIONAL PIECES ====================
    _p("etched-silver-beaded-napkin-ring", "Etched Silver Beaded Napkin Ring", "home-furnishing", "napkin-rings",
       16, "piece", "Silver-tone napkin ring with diagonal leaf etch and beaded edge.",
       "A wide-band silver-tone napkin ring featuring delicate diagonal palm/leaf engraving and beaded rim detailing. A polished, classic piece for formal dining.",
       None, [("napkin_rings", 22)]),
    _p("kundan-ruby-drop-necklace-set", "Kundan & Ruby Drop Choker Set", "artificial-jewelry", "necklaces",
       64, "set", "Square kundan choker with pear-shaped ruby drop.",
       "An exquisite gold-tone choker handset with square kundan glass stones and a central teardrop ruby stone, complete with matching stud drops. A timeless classic for festive attire.",
       "Bridal", [("jewellery", 8)]),
    _p("cz-solitaire-bridal-necklace-set", "CZ Solitaire Bridal Necklace Set", "artificial-jewelry", "necklaces",
       78, "set", "Shimmering cubic zirconia leaf-fringe necklace and drops.",
       "A sparkling silver-tone necklace set studded with marquise and brilliant-cut stones arranged in a delicate floral fringe, accompanied by matching drop earrings.",
       "Statement", [("ornaments", 23)]),
    _p("multicolour-chand-earrings", "Multicolour Gemstone Long Chand Earrings", "artificial-jewelry", "earrings",
       32, "pair", "Long articulated earrings in ruby, emerald and sapphire tones.",
       "A pair of statement articulated shoulder-duster earrings handset with multicolour gemstone-cut glass crystals. Lightweight with rich dramatic movement.",
       "Festive", [("jewellery", 8)]),
    _p("crescent-kundan-pearl-earrings", "Crescent Kundan & Pearl Hoop Earrings", "artificial-jewelry", "earrings",
       28, "pair", "Meenakari and kundan crescent hoops with pearl drops.",
       "Crescent-shaped gold-tone hoop earrings lined with ruby-pink meenakari enamel, kundan stones, and a fringe of dangling seed pearls. Perfect for festive celebrations.",
       "Handcrafted", [("ornaments", 23)]),
]
